cloudant/python-cloudant

CHANGES.rst
src/cloudant/database.py
src/cloudant/result.py
tests/integration/changes_test.py
tests/unit/mocked/database_test.py

_What:_
We need to fix the database object iterator so that it does not drop into an infinite loop when returning a set of documents that is greater than the fetch limit.  The database iterator also needs to return objects wrapped as Documents.  Finally the bulk_docs functionality needs to be clarified.
_Why:_
The iterator issue is a bug and needs to be fixed.  The bulk_docs functionality currently is redundant and confusing.
_How:_
- Fix iterator to not fall into infinite loop when documents being retrieved is greater than the fetch limit on the database object.
- Fix iterator to return a Document or a DesignDocument object.
- Fix iterator to attach a Document or a DesignDocument to the database object.
- Remove the current bulk_docs method from the database.py module.
- Rename the …

Fix database iterator and bulk docs method call

---

tests/unit/db/account_tests.py
tests/unit/db/database_tests.py
tests/unit/db/unit_t_db_base.py

_What:_
We are adding new common CouchDB and Cloudant database tests.
_Why:_
In order to more accurately test the CouchDatabase and CloudantDatabase class functionality we need to ensure that we have a solid set of unit tests that tests functionality against both CouchDB and Cloudant instances.
_How:_
- Add unit tests that are common to both Couch and Cloudant database implementations.
- Additional Cloudant database specific tests will be added in a future PR.
- Refactor the account module and introduce a unit test base class in order to consolidate common testing functionality.
reviewer: @gadamc
BugId: 54523

Add common database unit tests

---

CHANGES.rst
src/cloudant/account.py
src/cloudant/database.py
tests/unit/db/account_tests.py
tests/unit/db/database_tests.py
tests/unit/db/unit_t_db_base.py
tests/unit/mocked/account_test.py
tests/unit/mocked/database_test.py

_What:_
- Moved database API methods to appropriate locations.
- Moved db_update to account module.
- Moved missing_revisions, revisions_diff, get_revision_limit, set_revision_limit, and view_cleanup methods from CloudantDatabase to CouchDatabase class.
- Added common database tests for the methods mentioned above.
- Added Cloudant specific tests.
_Why:_
- The _db_update endpoint provides account level information.  Its db_update API method belongs in the account module.
- The methods moved to the CouchDatabase class work for both CouchDB and Cloudant instances.  They belong in the CouchDatabase class which the CloudantDatabase class extends.
- Tests needed to be added to thoroughly test all of the database functionality.
_How:_
- Moved database API methods to appropriate locations.
- …

Re-Organize database methods and add more database tests

---

src/cloudant/document.py
tests/unit/db/database_tests.py
tests/unit/db/document_tests.py
tests/unit/mocked/document_test.py

_What:_
- Add unit tests that check Document class functionality against a database.
- Enhance the Document class based on unit test results.
_Why:_
Unit tests that target a database provide a more accurate testing platform.
_How:_
- Add Document unit tests that test functionality against either a CouchDB or a Cloudant database.
- Change the Document class in the following ways:
- Only construct the document_url if the _document_id has a value.
- Only execute the exists() request if a _document_id has a value.
- Ensure that a create() request will only create and not update a document remotely.
- Ensure that a fetch() request replaces the entire dictionary contents of the current Document object. 
- Rename field_append to list_field_append, rename field_remove to list_field_remove, and …

Add document module unit tests and make Document class fixes

---

CHANGES.rst
src/cloudant/account.py
src/cloudant/replicator.py
tests/integration/replicator_test.py
tests/unit/db/replicator_tests.py
tests/unit/mocked/replicator_test.py

_What:_
- Refactor ReplicatorDatabase to Replicator.
- Add Replicator unit tests that target a Cloudant or CouchDB instance.
_Why:_
The new Replicator class has the database as an attribute so the Replicator provides an API that works with both a CloudantDatabase and a CouchDatabase _replicator database.
_How:_
- Based on the account client provided when constructing a Replicator object, the Replicator provides a user friendly API for replication tasks for either a Cloudant or a CouchDB account.
- The list_replications method now returns a list of Document wrapped objects.
- Update the integration/replicator_test.py module based on refactoring.
- Update the mocked/replicator_test.py module based on refactoring.
- Add Replicator tests that target a database instance.
reviewer: @emlaver …

Refactor the replicator and add tests

---

CHANGES.rst
src/cloudant/design_document.py
tests/unit/db/design_document_tests.py
tests/unit/db/document_tests.py

_What:_
Add DesignDocument unit tests that target database instances.
_Why:_
In order to adequately test DesignDocument functionality we need to have tests that run against CouchDB and Cloudant instances.
_How:_
- Ensure that each DesignDocument _id is prefaced with `_design/`.
- Create tests in design_document_tests that exercise all of the methods of the DesignDocument class.
reviewer: @emlaver
reviewer: @tomblench 
bugId: 55838

Add DesignDocument unit tests

---

tests/unit/db/views_tests.py

_What:_
Add unit tests that target database instance(s) for the views.py module.
_Why:_
In order to adequately test Views functionality we need to have tests that run against CouchDB and Cloudant instances.
_How:_
Add tests that test View functionality against a database instance.
reviewer: @rhyshort
reviewer: @tomblench 
BugId: 56328

Add views module unit tests

---

README.rst
docs/compatibility.rst
docs/index.rst
src/cloudant/__init__.py
src/cloudant/account.py
src/cloudant/changes.py
src/cloudant/credentials.py
src/cloudant/database.py

_What:_
Clean up the content found in docstrings throughout the codebase.  Session context helpers, account, changes, credentials, and database modules have been cleaned up in this PR.  Additional PR to follow with the remainder of the cleaned up docstring content.
_Why:_
In order for the documentation to appear as desired on readthedocs.org we needed to update the docstring content accordingly.
_How:_
Changes have been made to Session context helpers, account, changes, credentials, and database modules.  The changes made looked to standardize the way in which we presented each class and their methods to provide a more consistent look and feel to the documentation.
reviewer: @ricellis
BugId: 57063

Clean up docstring content

---

src/cloudant/design_document.py
src/cloudant/document.py
src/cloudant/errors.py
src/cloudant/replicator.py
src/cloudant/result.py
src/cloudant/views.py

_What:_
Clean up the content found in docstrings throughout the codebase.  design_document, document, errors, replicator, result, and views modules have been cleaned up in this PR.  This is part two of a two part PR.  Part one can be found at https://github.com/cloudant/python-cloudant/pull/34.
_Why:_
In order for the documentation to appear as desired on readthedocs.org we needed to update the docstring content accordingly.
_How:_
Changes have been made to design_document, document, errors, replicator, result, and views modules.  The changes made looked to standardize the way in which we presented each class and their methods to provide a more consistent look and feel to the documentation.
BugId: 57063
reviewer: @rhyshort
reviewer: @brynh

Clean up docstring content part #2

---

src/cloudant/query.py
tests/unit/db/database_tests.py
tests/unit/db/query_result_tests.py
tests/unit/db/query_tests.py

_What:_
This PR contains the unit tests for code added in https://github.com/cloudant/python-cloudant/pull/37
_Why:_
Unit tests needed to test code
_How:_
- Added Query unit tests
- Added QueryResult unit tests
- Added database convenience method unit tests for get_query_result
_Issue:_ #39 
reviewer: @ricellis
reviewer: @emlaver

Add query execution support - part two (tests)

---

src/cloudant/database.py
src/cloudant/design_document.py
src/cloudant/index_constants.py
src/cloudant/indexes.py
src/cloudant/query.py
src/cloudant/result.py
src/cloudant/views.py
tests/unit/mocked/design_doc_test.py

_What:_
Provide API to manage Cloudant Query JSON and TEXT indexes.  This PR contains only the code/logic for this functionality.  A follow-up PR(s) will include the unit tests which are complete and all run to successful completion.  The work has been split up to make the work easier to review.
_Why:_
In order to successfully use Cloudant Query, the ability to create and delete query indexes needs to be provided.
_How:_
- Add an indexes module that handles the creation and deletion of Cloudant Query indexes.
- Modify the views module and add a QueryIndexView class to handle the representation of a JSON index as a view in a design document.
- Modify the design_documents module to handle the new views module updates.
- Add API methods to the database module that provide an interface to …

Add query index management support

---

tests/unit/db/index_tests.py

_What:_
Add unit tests for the indexes module in support of #40.
_Why:_
To ensure that the indexes module logic is thoroughly tested.
_How:_
- Add an indexes_tests.py module.
- Add IndexTests class with tests for the Index class.
- Add SearchIndexTests class with tests for the SearchIndex class.
- Add SpecialIndexTests class with tests for the SpecialIndex class.
_Issues:_
- #74 in support of #40 
reviewer: @evansde77 
reviewer: @brynh

Add unit tests for the indexes module

---

pylintrc
src/cloudant/__init__.py
src/cloudant/account.py
src/cloudant/database.py
src/cloudant/design_document.py
src/cloudant/indexes.py
src/cloudant/result.py
tests/unit/mocked/lint_test.py

_What:_
Update the library code so that it will successfully pass the pylint 1.5.0 unit test.
_Why:_
Pylint helps us keep the code clean and following a standard.  The pylint 1.5.0 release introduced a few wrinkles that were not in place with the previous pylint 1.4.4 version we were using.  To keep current with pylint we needed to make these changes to the library.
_How:_
- Removed the assertion in the pylint unit test that checked STD_ERR for output.  This was a redundant check and pylint was issuing informational warnings there so we were getting test failure when there was nothing wrong.
- Update the pylintrc configuration as needed to work with 1.5.0.
- Refactored code based on pylint 1.5.0 findings.
- Set the pylint unit test to no longer be skipped as part of the CI.
_Issues:_
- …

Update library code based on pylint 1.5.0 findings

---

CHANGES.rst
docs/indexes.rst
docs/modules.rst
docs/query.rst

_What:_
We need to add .rst files to being in the docstring comments from the new indexes and query modules.
_Why:_
To provide documentation for the recently merged #39 and #40 Cloudant Query and index management functionality.
_How:_
- Added indexes.rst
- Added query.rst
- Updated modules.rst to include indexes and query in the TOC
- Updated changes.rst
_Issues:_
- #72 
- #39 
- #40 
reviewer @rhyshort

Update documentation to add Cloudant Query support

---

src/cloudant/document.py
tests/unit/db/design_document_tests.py
tests/unit/db/document_tests.py

_What:_
Ensure that if the document id of a document contains special characters that the document url generated from that document id is encoded appropriately.
_Why:_
A bug was discovered #32 that sites that you cannot use special characters such as `/` in the document id because it creates a problem in the document id because it is not being encoded correctly.  This fix resolves that issue.
_How:_
- Handle the url for a document by encoding the private `_document_id` attribute before using it to generate the `document_url`.
- Handle the url for a design document by stripping `_design/` from the start of `_document_id` and then encoding the remainder of the `document_id` before using it to generate the `document_url`.  This is being done in the Document class rather than the …

Fix document url so that it is appropriately encoded

---

CHANGES.rst
src/cloudant/database.py
tests/unit/db/database_tests.py

_What:_
Fix a bug with the database iterator so that the documents that it returns have a valid document_url property.  Previously it was not being set.
_Why:_
WIthout a document_url property the Document/DesignDocument cannot be used to update or delete the corresponding document in the remote database.
_How:_
When instantiating the Document/DesignDocument object in the database iterator we now pass in the document id to the Document/DesignDocument constructor so that the _document_id private variable is set correctly thereby ensuring the document_url will also be set correctly.
_Issues:_
- #50 
reviewer: @brynh

Fix database iterator to wrap documents correctly

---

src/cloudant/result.py
tests/unit/db/result_tests.py
tests/unit/mocked/result_test.py

*What*
- The group_level is mis-typed in our result module ARG_TYPES. It should be set to `(int, types.NoneType)` but is currently set to `basestring`. Issue #55.
- Add Result and python_to_couch test cases for option group_level as part of issue #42.
- Boolean values for group_level should throw an exception.
*How*
- Replace current group_level type `basestring` with `int`
- Throw Cloudant argument exception when a boolean value exists in a python_to_couch option, and the `ARG_TYPES` is expecting '(int, types.NoneType)`.
*Testing*
Add new test class that contains Result and python_to_couch testing with group_level option.
Future tests (#42) will be added for the existing python_to_couch options.
reviewer: @alfinkel
reviewer: @ricellis

Fix group_level type to `int` and add new test case class

---

CHANGES.rst
src/cloudant/database.py
src/cloudant/query.py
tests/unit/db/database_tests.py
tests/unit/db/query_tests.py

_What:_
Remove the enforcement of the `fields` as a required parameter for making a query.
_Why:_
Cloudant supports not passing in the `fields` when making a query. If no fields are provided then all the fields of each document are returned. This PR makes sure that python-cloudant mimics that behavior.
_How:_
- In `CloudantDatabase.get_query_result()` the `fields` parameter is checked for existence before instantiating the `Query`.
- In `Query.__call__` I removed the check for `fields` being `None` or empty.
_Tests:_
- The query callable tests that test for `fields` being empty or `None` were removed. 
- The tests were updated to treat `fields` as a `**kwargs` argument.
- Test that calling `db.get_query_result` handles a nonexistent `fields` parameter.
_Issues:_
- #86 
reviewer @alfinkel …

Remove the fields parameter from required Query parameters

---

CHANGES.rst
src/cloudant/database.py
tests/unit/db/database_tests.py
tests/unit/mocked/database_test.py

Fix the CloudantDatabase.share_database method to accept all valid roles when sharing a database.
- Change the method signature to accept roles as a list argument.
- Validate the roles provided against a list of valid roles.
- Updated tests to use the new method signature for shared_database
- Added new tests to validate new functionality introduced as part of this bug fix.
reviewer: @rhyshort
- #98

Fix CloudantDatabase.share_database method to accept all valid roles

---

CHANGES.rst
src/cloudant/database.py
tests/unit/db/database_tests.py

Fix the CouchDatabase.create_document method to handle design documents as well as documents.
Add a check to see if the data being used to create the document contains an `_id` that begins with `_design/`.  If it does then a DesignDocument object is passed back by the method and is attached to the locally cached database object.  Otherwise a Document object will be passed back and cached.
- Add assertions to existing tests to verify that a Document object is returned and locally cached when expected.
- Add a test to verify that a DesignDocument object is returned and locally cached when expected.
reviewer @rhyshort
reviewer @emlaver 
- #66

66 fix create doc to handle ddocs

---

CHANGES.rst
src/cloudant/database.py
src/cloudant/design_document.py
src/cloudant/indexes.py
src/cloudant/views.py
tests/unit/db/database_tests.py
tests/unit/db/design_document_tests.py
tests/unit/db/index_tests.py

We need to refactor the current SearchIndex class to be named TextIndex since it really refers to Cloudant Query text index and not a Cloudant Search index.  Also, we need to provide clearer naming for the database convenience methods of get_all_indexes, create_index, and delete_index to specifically reference the fact that these methods are meant for Cloudant Query (CQ) index management only.
The current name of SearchIndex is inaccurate as it really handles Cloudant Query text indexes and not actual Cloudant Search indexes and the database convenience methods used to manage the Cloudant Query indexes need clearer naming for the same reason.
- Rename SearchIndex to TextIndex and update all references to the class.
- Rename the get_all_indexes method of the CloudantDatabase class to be …

Refactor Cloudant Query index class and DB methods

---

.travis.yml
CHANGES.rst
src/cloudant/__init__.py
src/cloudant/account.py
src/cloudant/database.py
src/cloudant/replicator.py
tests/unit/db/account_tests.py
tests/unit/db/database_tests.py
tests/unit/db/replicator_tests.py
tests/unit/db/unit_t_db_base.py
tests/unit/mocked/replicator_test.py

Add support for CouchDB Admin Party mode where everyone is an Admin.
The default install of CouchDB uses Admin Party mode where everyone is Admin.  We needed to enable this library to work in this mode.
- Set CouchDB constructor user and auth_token arguments to default to None.
- Add an admin_party property to the CouchDB class that returns true if both user and auth_token are not defined. False otherwise.
- Add logic to handle processing differently for Admin Party in the CouchDB class. Methods include connect(), session(), session_cookie(), session_login(), session_logout(), and basic_auth_str().
- Add logic to handle processing differently for Admin Party in the CouchDatabase class, creds() method.
- Add logic to handle processing differently for Admin Party in the Replicator class, …

Add support for CouchDB Admin Party mode

---

CHANGES.rst
pylintrc
src/cloudant/database.py
src/cloudant/result.py
src/cloudant/views.py
tests/unit/db/database_tests.py
tests/unit/db/views_tests.py

Add logic so that any query using the `keys` parameter is handled via a http POST request instead of a http GET request.
- Update result module python_to_couch function so that it handles the keys argument separately.
- Update the CouchDatabase all_docs method logic to handle any call containing the keys argument as a http POST request.
- Update the Views \_\_call\_\_ method logic to handle any call containing the keys argument as a http POST request.
- Add tests to both database_tests.py and view_tests.py to check that the POST request processing is working as expected.  Tests were added to include a list of keys that would normally cause a similar GET request to fail due to url size limitations.
- The current pylint min-similarity-lines setting was increased from 4 to 5 since the 4 …

Use POST request with queries using the keys parameter

---

src/cloudant/result.py
tests/unit/db/param_translation_tests.py
tests/unit/mocked/result_test.py

Refactored the python_to_couch parameter translation code and added new validation and translation logic.
- Make all ARG_TYPES values be tuple type.  This adds to clarification of the python_to_couch valdidation code down stream.
- Split validation and translation logic into separate private functions for use by python_to_couch.
- Add validation logic to validate the content of the list elements provided to a keys parameter.
- Add translation logic to ensure that keys, endkey_docid, startkey_docid and stale parameters are not translated based on the settings in TYPE_CONVERTERS.
- Add tests to ensure that the conversion of parameters from Python to CouchDB is correct.
- Update the mocked result tests as they were asserting on invalid values previously.
NOTE:  Additional tests that validate …

Clean up python_to_couch code and add tests

---

tests/unit/db/view_execution_tests.py

Add view_execution_tests.py module to test that views using converted Python to CouchDB parameters return valid values.
Add tests for each valid parameter contained within the `ARG_TYPES` dictionary to ensure that the converted parameters yield the expected view query result set of data.
- Add the view_execution_tests.py module
- Add tests for each valid parameter and value to validate view query functionality using the translated parameters.
#112

Add view execution tests using translated parameters

---

src/cloudant/database.py
src/cloudant/views.py
tests/unit/db/database_tests.py

Combine `get_view_result` and `get_view_raw_result` into one method.
The default setting of get_view_result is `raw_result=False` and will return a Result object. 
If the user requires manually changing the paging and iteration, then they would use the setting `raw_result=True` and pass in the skip and/or limit parameter. 
The existing test case `test_retrieve_raw_view_results` that used the method `get_view_raw_result` now uses  `get_view_result` with `raw_result=True`.
Tests added to assert that the result contains the correct number of documents using `raw_result=True` and limit, skip, or both parameters.
reviewer: @alfinkel
#43

Combine get_view_result and get_view_raw_result into one method

---

CHANGES.rst
docs/getting_started.rst
src/cloudant/database.py
src/cloudant/errors.py
src/cloudant/result.py
src/cloudant/views.py
tests/unit/db/query_result_tests.py
tests/unit/mocked/result_test.py

Add result collection key/index access, key/index slicing and iteration validation logic to the Result class and update supporting documentation.
- Add a ResultException class to handle all Result specific exceptions.
- Add logic to Result `__getitem__()` to handle data access via index.  As in `result[10]` will return the data in position 10 of the result collection.
- Add validation logic to key slicing to ensure that invalid requests are caught.
- Update iteration logic validation to use ResultException.
- Update "Dealing with Results" section of the "Getting Started" documentation.
- Update all affected docstring content in database, views, and result modules.
All tests have been written and the new tests all pass successfully under Python 2.7 and 3.5 targeting both CouchDB as well as …

Add Result class validation

---

CHANGES.rst
src/cloudant/account.py
tests/unit/db/account_tests.py

In the account module, the Cloudant._usage_endpoint() method should only accept either both a year and a month or nothing.
If both year and month exist, create endpoint request with both parameters. 
If either year or month do not exist, raise a CloudantException.
Additional test cases to assert that CloudantException is raised when only year parameter exists for `bill`, `requests_usage`, and `volume_usage`. 
reviewer @alfinkel 
reviewer @mikerhodes 
#59

Fix Cloudant._usage_endpoint() to only accept both year and month or neither

---

src/cloudant/result.py
tests/unit/db/result_tests.py
tests/unit/db/unit_t_db_base.py
tests/unit/db/view_execution_tests.py

Add unit tests to ensure that the Result class logic is tested thoroughly
- Made a create_views() helper test function available to all test subclasses of UnitTestDbBase
- Added tests for ResultException
- Added tests for Result data access via index value
- Added tests for Result data access via key value
- Added tests for Result data access via index slicing
- Added tests for Result data access via key slicing
- Added tests for Result data access via iteration
- Added tests for ResultException
- Added tests for Result data access via index value
- Added tests for Result data access via key value
- Added tests for Result data access via index slicing
- Added tests for Result data access via key slicing
- Added tests for Result data access via iteration
reviewer: @rhyshort 
reviewer: …

Add result class unit tests

---

CHANGES.rst
src/cloudant/result.py
tests/unit/db/query_result_tests.py

Added the ability to access data from a QueryResult by using an index value.  As in:
```python
result = QueryResult(...)
result[0]             # Retrieves the 1st document in the query result
result[9]             # Retrieves the 10th document in the query result
```
Also relaxed skip/limit restrictions on QueryResult slicing.  Now skip and/or limit can be used in the original Query or the customized QueryResut.
- Added logic to handle the processing of a single integer value as the key of a QueryResult.
- Removed logic that raised exceptions when either `skip` or `limit` were encountered in the Query or the QueryResult custom options.
- Refactored and added additional QueryResult tests to ensure that all functionality is working as expected.
reviewer: @brynh 
- #110

Add QueryResult data access by index value

---

docs/client.rst
docs/getting_started.rst
docs/modules.rst
src/cloudant/__init__.py
src/cloudant/changes.py
src/cloudant/client.py
src/cloudant/replicator.py
tests/unit/db/client_tests.py
tests/unit/db/database_tests.py
tests/unit/db/replicator_tests.py
tests/unit/db/unit_t_db_base.py
tests/unit/mocked/client_test.py
tests/unit/mocked/database_test.py
tests/unit/mocked/document_test.py
tests/unit/mocked/replicator_test.py

Rename the account module to be the client module.
The notion of an account is clear when it comes to Cloudant but less so when it comes to CouchDB.  Since this library serves both, we are switching the name of the account module to client so that it makes sense for both Cloudant and CouchDB.
- Rename account.py as client.py
- Update all import references in code and tests
- Update documentation .rst files
- Update docsting comments as necessary to reference client instead of account
- No additional tests but all tests using account module now use client module
- Comments updated as necessary
reviewer: @rhyshort 
- #44

Rename account.py to client.py

---

docs/modules.rst
docs/view.rst
src/cloudant/database.py
src/cloudant/design_document.py
src/cloudant/result.py
src/cloudant/view.py
tests/unit/db/design_document_tests.py
tests/unit/db/index_tests.py
tests/unit/db/view_tests.py
tests/unit/mocked/view_test.py

Rename views.py to view.py to match naming pattern for modules within this library.
#132 
- Rename views.py to view.py
- Update all import references in code and tests
- Update Sphinx documentation .rst files
- Update docsting comments
- No additional tests
- All tests using views module now use view module
reviewer @alfinkel 

Rename views.py module to view.py

---

CHANGES.rst
src/cloudant/database.py
src/cloudant/query.py
src/cloudant/result.py
src/cloudant/view.py
tests/unit/db/database_tests.py
tests/unit/db/query_tests.py
tests/unit/db/view_tests.py

The make_result method in Query and View classes is redundant and confusing. It should be removed. A Result/QueryResult object can be stood up that essentially would perform the same functionality. Likewise the database convenience methods of get_view_results and get_query_results also perform the same functionality.
In database.py module:
- change get_view_results to standup a new Result object passing it **kwargs.
- change get_query_results to standup a new QueryResult object passing it **kwargs.
In result.py module:
- Move parameter docs from make_result methods to Result/QueryResult class docstring.
- Remove references to make_result in comments.
In view.py module:
- Remove make_result.
- Refactor custom_result to use a new Result object passing it **kwargs.
- Add …

Remove make_result from Query and View

---

src/cloudant/client.py
src/cloudant/database.py
src/cloudant/feed.py
tests/unit/db/client_tests.py
tests/unit/db/database_tests.py
tests/unit/db/infinite_feed_tests.py

Added the ability for a feed (_changes or _db_updates) to return an infinite iterator.
Anytime a last sequence identifier is encountered for a `continuous` feed another HTTP request stream is made to the server thus creating a perpetually refreshed feed.  This was done by extending the Feed class as an InfiniteFeed class.  The InfiniteFeed has added logic in the `next()` method call to check for a last sequence identifier and if found to re-issue the HTTP request with a new `since` option set to the last sequence identifier.
The InfiniteFeed implementation is only valid for CouchDatabase and CloudantDatabase _changes feeds and the Cloudant _db_updates feed only.  The CouchDB _db_updates feed does not return a last sequence identifier and does not accept `since` as an option so the client …

Add infinite feed implementation

---

src/cloudant/client.py
src/cloudant/database.py
src/cloudant/document.py
src/cloudant/feed.py
src/cloudant/query.py
tests/unit/client_tests.py
tests/unit/database_tests.py
tests/unit/db_updates_tests.py
tests/unit/infinite_feed_tests.py

A number of the CouchDB specific classes have public and private attributes with "cloudant" as part of their name.  This PR removes "cloudant" references from those attributes to make things clearer from a useability and maintenance point of view.
- Rename client module CouchDB class attributes referencing Cloudant
- Rename database module CouchDatabase class attributes referencing Cloudant
- Rename document module Document class attributes referencing Cloudant
- Rename feed module Feed/InfiniteFeed class attributes referencing Cloudant
- Rename query module Query class attributes referencing Cloudant
- Rename cloudant references in tests as needed based on above.
reviewer: @rhyshort 
reviewer: @brynh 
- #58

Rename cloudant attribute references in couchdb classes

---

src/cloudant/client.py
tests/unit/client_tests.py

Update User-Agent format to be `python-cloudant/<library version>/Python/<Python version>/<OS name>/<OS architecture>`.
So an example User-Agent will look like `python-cloudant/2.0.0/Python/2.7.10/Darwin/x86_64`.
- Update the _USER_AGENT setting in the client.py
- Update the client test that tests the connection specifics to include checks for the User-Agent string components.
reviewer: @ricellis 
- #150

Update user agent format

---

CHANGES.rst
src/cloudant/client.py

Added backoff/retry for 429 status codes.
Use the request library's built in `HTTPAdapter`to provide retry configuration to the underlying urllib3 library. Configure for 10 retries starting at a 250 ms backoff for all CouchDB HTTP methods. Use 0 retries for connection and read so these retries apply only to the `status_forcelist` which includes only the 429 status code, so no other retry behaviour is affected by the change.
No new tests, provides configuration to underlying library. Existing tests would fail if configuration syntax was wrong. Testing the actual retry function would require adding a mock server. The pattern in python-cloudant has been to avoid testing underlying library code in this way. I have manually verified that the retry functions. 
reviewer: @alfinkel
reviewer: …

60008 429 backoff

---

CHANGES.rst
src/cloudant/_common_util.py

Fixed compatibility issue with windows.
Removed usage of `os.uname` for the user-agent string.
No new tests, running on Windows is enough to confirm fix.
Fixes #163

Remove usage of os.uname since it is unavaiable on windows.

---

CHANGES.rst
README.rst

- Update the doc links in the README because readthedocs.org are moving the documentation sub-domains to readthedocs.io.
- The current link to the library documentation in the README.rst is set to http://python-cloudant.readthedocs.org. This resolves to http://python-cloudant.readthedocs.org/index.html which is actually our index module documentation. This link should go to the default.html documentation home page.
- Update readthedocs link from index module to default documentation page
- Update doc links in README from readthedocs.org to readthedocs.io
No test cases needed.
fixes #155 
fixes #161

Update readthedocs links

---

CHANGES.rst
src/cloudant/_common_util.py
src/cloudant/database.py
tests/unit/database_tests.py
tests/unit/unit_t_db_base.py

Support Cloudant search query parameter processing and execution.
- Handled search query parameter processing and execution in `CloudantDatabase.get_search_result`
- Added dictionary of search query parameters in common_util
- Unit tests for search index query in `CloudantDatabaseTests` class
- Created a search index during test class setup for querying tests with `create_search_index`
reviewer: @alfinkel 
#158

Cloudant search index query

---

CHANGES.rst
src/cloudant/design_document.py
tests/unit/database_tests.py
tests/unit/design_document_tests.py
tests/unit/index_tests.py

Functions for managing Cloudant search index in design documents module. 
- Added functions for search index management in `design_document.py`
- New indexes property for the locally cached DesignDocument in `design_document.py`
Unit test cases to assert new search index management functions in `DesignDocumentTests`
Added `indexes` key with empty dictionary value to locally cached design documents in existing test case assertions.
fixes #159 
fixes #104

Cloudant Search index management

---

CHANGES.rst
src/cloudant/design_document.py
tests/unit/design_document_tests.py

Support URL rewriting with ``rewrites`` property in design document module. Documentation and an example are included with the property accessor.
- Added ``rewrite`` accessor property with docstring that includes documentation
Added test case for using ``rewrite`` property in DesignDocumentTests.
Created local sphinx build to review documentation.
@tomblench
fixes #175

Rewrite rules property in design_document.py

---

src/cloudant/_common_util.py
src/cloudant/database.py
src/cloudant/document.py
src/cloudant/view.py

There's an almost identical block of code in `View.__call__` and `database.all_docs` that's been moved into `get_docs` method in the common_util module.
The new common util `get_docs` method also accepts `encoder` for use with a custom ``JSONEncoder`` subclass.
- Moved duplicated code for GET/POST request to internal method `get_docs`
- Changed visibility of `Document` attribute `encoder` for use in  `View.__call__`
No new test cases required. 
fixes #182 
fixes #170

Move duplicated code to common_util.py

---

CHANGES.rst
docs/adapters.rst
docs/modules.rst
src/cloudant/adapters.py
src/cloudant/client.py
tests/unit/adapter_tests.py

Made 429 replays optional and configurable.
Some users would prefer to receive an error earlier than the current 429 replay behaviour.
Added support for `adapter` argument on client constructors.
Moved 429 `HTTPAdapter` configuration into `Replay429Adapter` class in
`cloudant.adapters`.
Added `retries` and `initialBackoff` args to `Replay429Adapter`.
Updated docs including `CHANGES.rst` and for new `adapters` module.
Added tests for init and adding adapter with `Replay429Adapter` and args.
Manually tested that the behaviour is as expected with a 429 response.

Made 429 replays optional and configurable

---

CHANGES.rst
src/cloudant/_common_util.py
src/cloudant/database.py
src/cloudant/design_document.py
tests/unit/database_tests.py
tests/unit/design_document_tests.py
tests/unit/index_tests.py

Add support for managing and querying list functions.
Avoid repeating if statements for each property in design document’s `save` and `fetch` functions by looping through a set containing the properties.
- Handled list function execution against the _list endpoint in CouchDatabase.get_list_result
- Added support for managing list functions in design document
- Added HTTP Headers argument to `get_docs` method signature
- Replaced repeating if statements for each property with for-loop over a set of all properties
Unit test cases to assert new list function management in DesignDocumentTests.
Unit test cases to assert `get_list_result` in DatabaseTests.
fixes #178

Added support for list functions

---

CHANGES.rst
src/cloudant/design_document.py
tests/unit/design_document_tests.py

Support geospatial indexes (Cloudant Geo) with ``st_indexes`` property in design document module.
Documentation and examples are included with the property accessor.
- Added Cloudant Geo st_indexes property with documentation and example
Added test case in DesignDocumentTests.
Created local sphinx build to review documentation.
fixes #188

Cloudant Geo property in design_document.py

---

CHANGES.rst
src/cloudant/database.py
src/cloudant/design_document.py
tests/unit/database_tests.py
tests/unit/design_document_tests.py
tests/unit/index_tests.py

Add support for managing and querying show functions.
- Handled show function execution against the _show endpoint in `CouchDatabase.get_show_function_result`
- Added support for managing show functions in design document
Unit test cases to assert show function management in DesignDocumentTests.
Unit test cases to assert `get_show_function_result` in DatabaseTests.
fixes #186

Added support for show functions

---

CHANGES.rst
src/cloudant/database.py
src/cloudant/design_document.py
tests/unit/database_tests.py

Support executing update handler functions.
- Added ``updates`` property with documentation and example
- Handled update handler execution against the `_update` 
endpoint in `update_handler_result`
Added unit tests for `update_handler_result` in DatabaseTests.
fixes #193

Added support for update handlers

---

CHANGES.rst
src/cloudant/design_document.py
tests/unit/design_document_tests.py

Support update validators with ``validate_doc_update`` property in design document module.
Documentation and an example are included with the property accessor.
- Added ``validate_doc_update`` property with documentation
Added unit test in DesignDocumentTests.
fixes #197

Added support for update validators

---

CHANGES.rst
src/cloudant/_common_util.py

Added Content-Type header to requests using POST for the keys param.
Added `Content-Type: application/json` to `headers` in `src.cloudant._common_util.get_docs`.
This is covered by existing tests:
`tests.unit.database_tests.DatabaseTests#test_all_docs_post`
`tests.unit.database_tests.DatabaseTests#test_all_docs_post_multiple_params`
Fixes #177

Added Content-Type header for keys POST cases.

---

src/cloudant/design_document.py

Support filter functions with property accessor in design document module.
- Added ``filters`` property with documentation
No new tests.
Unit test exists in ``changes_tests.py``:
https://github.com/cloudant/python-cloudant/blob/1986cfb4d801049e89218d349c5ab9e241e97555/tests/unit/changes_tests.py#L390
fixes #201

Filter functions property in design_document.py

---

CHANGES.rst
src/cloudant/_common_util.py
tests/unit/client_tests.py
tests/unit/database_tests.py
tests/unit/design_document_tests.py
tests/unit/index_tests.py
tests/unit/result_tests.py

Resolved Cloudant service test issues.
* Fixed allowed types for group_sort
* Updated billing tests
* Used the current month as a data range to prevent any issues with no data with future test account changes.
* Added new `bill_type` field.
* Used sort for search tests because the results need to be in a guaranteed order to be able to assert they are the same as expected, that means we need a sort or group_sort. 
* Fixed design document tests for newer Cloudant version
* test_get_info: Removed Cloudant/Couch 2 fields from comparison & removed Cloudant design doc name change that is not needed.
* test_geospatial_index: Removed `rev` property from row result before comparison.
* Removed `w` parameter from index creation test request options (we don't know how many nodes we will be testing …

205 cloudant tests

---

CHANGES.rst
src/cloudant/_common_util.py
src/cloudant/client.py
tests/unit/document_tests.py

Appended error and reason message to HTTPError exception.
- Utilized event hooks in requests to manipulate the response error message.
- New util method `append_response_error_content` that handles appending to the response message.
Added unit test in DocumentTests.
#65 
#195

Additional error details appended to HTTPError exception 

---

src/cloudant/database.py
tests/unit/database_tests.py

Added support for executing search queries with the `q` parameter.
Allow for `q` or `query` but not both parameters in `get_search_result` method
- Added `q` parameter in `get_search_result` documentation
Added test cases in CloudantDatabaseTests.

Add 'q' query parameter for Cloudant Search

---

tests/unit/database_tests.py

View cleanup is now automatically done in Cloudant.  When running tests against Cloudant, the test case `test_view_clean_up` should be skipped.
- Added `@unittest.skipIf` to skip the test case when running against Cloudant
No new test cases required.
fixes #215

Skip view cleanup test when running against Cloudant

---

CHANGES.rst
src/cloudant/database.py
src/cloudant/design_document.py
src/cloudant/document.py
tests/unit/database_tests.py
tests/unit/design_document_tests.py
tests/unit/document_tests.py

- `exists()` methods for both CouchDatabase and Document return `False` if response code is not 200.  Logic was added to call `raise_for_status()` for HTTP errors that are not 200 or 404.
- Added `raise_for_status()` for methods using `requests` that did not include this statement 
- Called `raise_for_status` when status code is not 200 or 404
- Added missing instances of `raise_for_status` in `database.py` and `design_document.py`
Added unit tests for asserting a bad request is raised when calling `Document.exists()` and `Database.exists()` methods.
#65 
fixes #216 
fixes #219

Added raise_for_status to improve error handling

---

src/cloudant/_common_util.py
tests/unit/database_tests.py

Added `q` entry into `SEARCH_INDEX_ARGS` so that `q` would be recognized as a valid search parameter by the database `get_search_results` method.
- Added `'q': (STRTYPE, int)` to _common_util.py `SEARCH_INDEX_ARGS` dictionary.
- Fixed the `test_get_search_result_executes_search_q` database test to use `q` instead of `query`.
#225

Fix q parameter search query bug

---

src/cloudant/client.py
tests/unit/client_tests.py
tests/unit/unit_t_db_base.py

Added the auto connect feature to the client constructor.
Added the `connect` keyword argument to the client `__init__`.  If `True` then perform the `connect` logic.  Default behavior is not to perform `connect` so current behavior is not compromised.
- Added auto connect tests to client_tests.py
- #230

Add auto connect feature to client

---

CHANGES.rst
src/cloudant/client.py
src/cloudant/database.py
src/cloudant/document.py
tests/unit/client_tests.py
tests/unit/database_tests.py
tests/unit/document_tests.py
tests/unit/replicator_tests.py

After disconnecting from a client any objects created based on that client like Database or Document objects are still able to make requests to Cloudant/CouchDB.
- Removed auth attribute from r_session so objects created based on the client are not able to make requests
- Added `r_session` property in `database.py` and `document.py`
Added test to assert a 401 status code when trying to access a databases's document count after disconnecting from the client.
fixes #218

Fix request session so all requests fail after client is disconnected

---

CHANGES.rst
src/cloudant/client.py
src/cloudant/database.py
src/cloudant/index.py
tests/unit/database_tests.py
tests/unit/index_tests.py
tests/unit/unit_t_db_base.py

Honour the JSON encoder passed to the client at construction when transforming data into JSON.
Specify the `cls` parameter for `json.dumps` calls which omitted it.
Tests added which use a string for encoder to force a `TypeError` to be thrown.
Fixes #221

Honour the custom encoder parameter for json encoding.

---

CHANGES.rst
Jenkinsfile
docs/modules.rst
docs/security_document.rst
src/cloudant/database.py
src/cloudant/security_document.py
tests/unit/database_tests.py
tests/unit/security_document_tests.py
tests/unit/unit_t_db_base.py

Added the ability to retrieve a security document from a specific database and to update that document as necessary.
- Add a SecurityDocument class that can: 
- fetch the security document content remotely
- save updated content to the server
- a context manager is also provided
- Add the database convenience method get_security_document
- Add security document tests
- Add get_security_document database test
- Fix Jenkinsfile to remove unnecessary ADMIN_PARTY export which fixes the security document tests
#52 
#227

Add security document management support

---

src/cloudant/_2to3.py
src/cloudant/_common_util.py
src/cloudant/client.py
tests/unit/auth_renewal_tests.py
tests/unit/client_tests.py
tests/unit/database_tests.py
tests/unit/unit_t_db_base.py

Add a session automatic renewal option to the `Session` object used by this library so that in the event of a request being made using expired session authentication credentials, the auth is renewed and the request is re-tried.
- Sub-class `requests.Session` as `InfiniteSession` class and handle a 401 response as needed
- Add the auto_renew keyword argument to client constructor to allow for auto renewal of session auth
- Current set of unit tests all pass
- Manual tests to validate functionality were successful against Cloudant
- Add client unit tests to test client auto renewal functionality
- Add additional auth renewal tests
#235

Add session auto-renewal option

---

CHANGES.rst
src/cloudant/replicator.py
tests/unit/replicator_tests.py

Correctly transform a UUID object into a string for replication documents.
Transfer the UUID object into a string by using the `str` method,
One test added `test_replication_with_generated_id`.
Fixes #242

Correctly transform UUID object into a string.

---

CHANGES.rst
src/cloudant/feed.py

Changed Feed.next() and InfiniteFeed.next() to iterate over skipped lines rather than recursing over them.
Use a while loop in Feed.next() and InfiniteFeed.next(). This unfortunately results in a few lines of duplicated code as there was no clear way to make use of calling the superclass method.
Functionality does not change, other than to tidy up stack traces and prevent overflow, so no tests are altered.
This fixes issue #245 where recursion can cause a stack overflow.

Iterate over skipped changes lines

---

tests/unit/database_tests.py
tests/unit/design_document_tests.py
tests/unit/document_tests.py

Fixed tests that failed because of ordering issues or behaviour differences between CouchDB 1.6 and newer versions.
* Fixed `test_appended_error_message_using_save_with_invalid_key` to check for `400 Bad Request`, but allowed to continue passing with 500 for CouchDB 1.6.x.
* Make test_get_search_result_without_query assertions order independent 
* Made test_get_search_info checks not rely on indexing completion
Fixes #251

251 fix tests

---

src/cloudant/_common_util.py

As part of reviewing the error handling of the library (#65), this method wasn't handling the ValueError from `response.json()` in the most efficient manner. 
It's also confusing to see the `**kwargs` that appears to be unused but is required as part of the event hook. 
- Improved logic for appending additional error message
- Updated docstring to include why `response` and `kargs` are necessary
No new tests and all existing tests are passing.
#65

Improved logic for appending http error and message

---

tests/unit/client_tests.py
tests/unit/replicator_tests.py

Fixes a couple of unreliable unit tests:
- _ClientTests.test_keys_
Mismatch results from`/_all_dbs` due to multiple test runners sharing the same CouchDB instance.
- _ReplicatorTests.test_list_replications_ (see #256)
Failing to delete a replication document. Document receives multiple updates from the replicator often causing delete attempts to _409_.
- _ClientTests.test_keys_
Assert keys contains 10 new test databases.
- _ReplicatorTests.test_list_replications_
Implement retrying on replication document deletion failures.
Fixes #256.

Fix unreliable unit tests

---

src/cloudant/__init__.py
src/cloudant/_common_util.py
tests/unit/cloud_foundry_tests.py

Pass the VCAP_SERVICES variable as an argument rather than pulling it
from the environment. This allows the application to retrieve it from
different sources and avoids the library dictating deployment policy to
the consuming application.
Adds additional unit tests.
Fixes #254.

Take VCAP_SERVICES env as arg in client builder

---

tests/unit/unit_t_db_base.py

It's hard to tell which test case are failing with the current test database naming scheme when databases are left behind in the test account from a failing test.  We should include the test case method in the test database name.
- Included test method name to test database name
No new tests.
fixes #248

248 some test not cleaning of databases

---

src/cloudant/_messages.py
src/cloudant/client.py
src/cloudant/database.py
src/cloudant/design_document.py
src/cloudant/document.py
src/cloudant/error.py
src/cloudant/feed.py
src/cloudant/index.py
src/cloudant/replicator.py
tests/unit/client_tests.py
tests/unit/database_tests.py
tests/unit/design_document_tests.py
tests/unit/document_tests.py
tests/unit/index_tests.py
tests/unit/infinite_feed_tests.py
tests/unit/replicator_tests.py

Using `ResultException` as an example, we can improve the error handling design by having class exceptions for modules that currently contain `CloudantException`, and by moving the error messages from `error.py` and other moduless to an internal `messages.py` module to reduce clutter.
- New exception classes for client, database, design document, document, feed, index, replicator modules
- All CloudantException and ResultException messages moved to _messages.py module
- Added status codes to all exception messages.
- 4xx for status codes that resembles a typical response code and 1xx for other status codes.  
- Removed duplicate error message in `Client._usage_endpoint` by using boolean
- Fixed up exception messages in modules
Fixed up exception messages in test cases.
Added new test …

259 improve error handling design

---

test-requirements.txt
tests/unit/database_tests.py
tests/unit/replicator_tests.py

Couple of minor test fixes,
- Altering the database N & Q values has changed the second element in the search result `order` array. This second element is only for troubleshooting and can be ignored in the tests (see https://docs.cloudant.com/search.html#query-syntax).
- Add some retrying around `test_create_replication` using Flaky.

Fix failing tests

---

src/cloudant/_common_util.py
src/cloudant/_messages.py
src/cloudant/client.py
src/cloudant/database.py
src/cloudant/design_document.py
src/cloudant/error.py
src/cloudant/feed.py
src/cloudant/index.py
src/cloudant/query.py
src/cloudant/view.py
tests/unit/client_tests.py
tests/unit/database_tests.py
tests/unit/design_document_tests.py
tests/unit/infinite_feed_tests.py
tests/unit/view_tests.py

This is a continuation of PR #264 for improving the error handling design by moving CloudantArgumentError messages to `messages.py` module and adding CloudantViewException in `error.py`.
- Added CloudantViewException to error.py and moved view exception messages to _messages.py
- Moved Cloudant argument messages to _messages.py
- Updated error messages in _messages.py and test cases for consistency
Fixed up exception and error messages in test cases.
Added new test cases for CloudantViewException.
fixes #65 
fixes #266

266 improve cloudant argument and exception

---

docs/getting_started.rst

- Added a note to use `Replay429Adapter` if retrying requests is needed after a 429 error
- Added `client` construction example that's configured with 429 adapter
No tests added.
fixes #249

249 add note and example for 429 adapter in getting_started.rst

---

tests/unit/unit_t_db_base.py

Admin party is now supported by the library and the docstring [here](https://github.com/cloudant/python-cloudant/blob/master/tests/unit/unit_t_db_base.py#L80-L82) should be removed.
- Removed admin party docstring in `unit_t_db_base.py`
No new tests.
#228

228 remove misleading admin party docstring

---

src/cloudant/_2to3.py
src/cloudant/_common_util.py
tests/unit/_test_util.py
tests/unit/database_tests.py
tests/unit/param_translation_tests.py

- Added `LONGTYPE` in `_2to3.py` to support `long` in `common_util` argument types
- Added `long` testing in existing parameter translation tests
- Added `test_all_docs_get_with_long_type` test case 
fixes #237

237 add Python 2 long type support to argument types

---

CHANGES.rst
docs/getting_started.rst
src/cloudant/_common_util.py
src/cloudant/client.py
tests/unit/client_tests.py
tests/unit/replicator_tests.py
tests/unit/unit_t_db_base.py

Allow for a timeout argument in `client` construction to prevent python-cloudant waiting forever for a HTTP connection or a response on all requests.
- ClientSession class to add timeout of to all requests
New tests to assert that connect and read timeout exception occurs during client construction and replication.
fixes #257

257 timeout argument

---

CHANGES.rst
src/cloudant/database.py

Correctly specify the custom JSON encoder.
To use a custom JSONEncoder subclass (e.g. one that overrides the default() method to serialize additional types), specify it with the cls kwarg; otherwise JSONEncoder is used.
Note, as of Python 3.6 the `json.dump` optional parameters are keyword-only. In earlier versions the additional argument was silently ignored.
Fixes #282.

Correctly specify custom JSON encoder

---

CHANGES.rst
src/cloudant/_messages.py
src/cloudant/client.py
tests/unit/client_tests.py

Replaced the existing exception error code of 409 with 412 when the database already exists.
- Updated error code to 412 in `_messages` and `client.create_database`
No new tests.
Updated existing `test_create_existing_database` test to assert the correct 412 exception.
fixes #287

287 throw exception with 412 code when db exists 

---

src/cloudant/_common_util.py
src/cloudant/client.py
src/cloudant/database.py
src/cloudant/result.py
tests/unit/database_tests.py

Catch error if `throw_on_exists` flag is set to `False` for document create.
Add new `throw_on_exists` boolean param to the `Document.create` method. Note that default behaviour is unchanged.
Includes additional unit test `test_create_document_that_already_exists`.
- #291

291 doc throw on exists

---

CHANGES.rst
src/cloudant/_common_util.py
tests/unit/database_tests.py

Fix `/_all_docs` call where `keys=[]`.
The `get_docs` common function was incorrectly dropping the `keys` parameter if the value of `keys` was an empty list.
Includes additional unit tests.
- #289

Fix _all_docs call where keys is an empty list

---

src/cloudant/adapters.py

Fix pylint import error in `adapters.py`.
Import `Retry` directly from `urllib3.util`.

Fix pylint import error in adapters.py

---

CHANGES.rst
src/cloudant/_common_util.py

What was changed, e.g. Added support for querying views.
- fixed crash on non-UTF8 chars in design docs
- fixed by encoding to UTF8
How to test your changes work, not required for documentation changes.
Setup faulty view with `couchapp`
```bash
mkdir test
cd test
couchapp init
couchapp generate view foo
couchapp push http://admin:password@localhost:5984/foo
```
`test.py`:
```python
from cloudant import couchdb_admin_party
from cloudant.design_document import DesignDocument
with couchdb_admin_party(url="http://localhost:5984") as couch:
db = couch.get('foo', remote=True)
ddoc = DesignDocument(db, '_design/test')
ddoc.fetch()
```
cause error:
```bash
$ python test.py 
Traceback (most recent call last):
File …
```

non-UTF8 chars (like \u2013) in your map/reduce will make the ddoc fetch puke

---

src/cloudant/_common_util.py
src/cloudant/adapters.py

Encode unicode strings as UTF-8 in Py2.
No additional tests added.
Fixes #301.

Fix pylint failure on Py3

---

CHANGES.rst
src/cloudant/_2to3.py
src/cloudant/database.py
tests/unit/database_tests.py

Fix bad `startkey` parameter in `/_all_docs` iterator.
Initially use `u'\u0000'` as a `startkey` parameter. With each batch, update the `startkey` to `docs[-1]['id'] + u'\u0000'`. 
This means that fetching an additional document per batch to act as the next `startkey` is now unnecessary.
Includes additional `/_all_docs` test.
Fixes #304.

304 fix bad startkey in all doc iter

---

CHANGES.rst
src/cloudant/feed.py
tests/unit/changes_tests.py

Fix changes feed validation to allow for the valid value `0` for `since` option.
- Fixed exception check so that value `0` for changes feed option `since` is valid
Added test case in `changes_tests.py`
fixes #297

297 changes feed since option

---

CHANGES.rst
src/cloudant/client.py
tests/unit/client_tests.py

Implement `Cloudant.bluemix()` client class method. 
```python
import os
from cloudant.client import Cloudant
c = Cloudant.bluemix(os.getenv('VCAP_SERVICES'), 'Cloudant NoSQL DB')
```
Includes additional unit tests.
Fixes #313.

Implement Cloudant.bluemix client class method

---

CHANGES.rst
src/cloudant/client.py
src/cloudant/database.py
src/cloudant/document.py
src/cloudant/index.py
src/cloudant/query.py
src/cloudant/view.py
tests/unit/database_tests.py
tests/unit/document_tests.py
tests/unit/index_tests.py
tests/unit/query_tests.py
tests/unit/view_tests.py

Use `'/'.join()` to concatenate URL parts.
Updated `posixpath.join` references to use `'/'.join` when concatenating URL parts.
Fixes #127.

Use `'/'.join()` to concatenate URL parts

---

docs/getting_started.rst
src/cloudant/_2to3.py
src/cloudant/__init__.py
src/cloudant/_common_util.py
src/cloudant/client.py
tests/unit/auth_renewal_tests.py
tests/unit/client_tests.py
tests/unit/iam_auth_tests.py

Add IAM authentication support.
Added a class method and context manager to simplify IAM client construction:
```python
from cloudant.client import Cloudant
client = Cloudant.iam('account_name', 'api_key_here', connect=True)
print client.all_dbs()
from cloudant import cloudant_iam
with cloudant_iam('account_name', 'api_key_here') as client:
print client.all_dbs()
```
Under the hood there's a new `use_iam=True` toggle. Once enabled, the `password` parameter is used as the IAM API key.
__IAM Authentication Workflow:__
1. Exchange IAM API key for access token via `IAM_TOKEN_URL`.
2. Generate a cookie from the access token using the `POST /_iam_session` Cloudant endpoint.
3. Use the _IAMSession_ cookie in all library requests.
4. Attempt to renew if the _IAMSession_ cookie has expired or on …

303 support iam auth

---

CHANGES.rst
src/cloudant/result.py
tests/unit/result_tests.py

Add ``Result.all()`` convenience method.
Performs same functionality as `result[:]`.
Includes additional unit test.
Fixes #233.

Add ``Result.all()`` convenience method

---

CHANGES.rst
README.rst
src/cloudant/database.py
src/cloudant/design_document.py

Updated `docs.cloudant.com` links to the latest Bluemix `console.bluemix.net/docs/` documentation.
- Replaced all deprecated links in library with the appropriate Bluemix doc links
- Replaced `Cloudant for developers` with `Cloudant Learning Center` link
- Changed wording in endpoint access link from 'documentation' to 'section'
No new tests.
Tested and verified all new links on local Sphinx build.
fixes #333

Updated deprecated docs.cloudant.com links

---

tests/unit/database_tests.py
tests/unit/index_tests.py

Following a patch to Mango the returned index JSON now includes additional
keys/values. To ensure the tests continue to pass on both old & new versions we
opt to inspect the returned JSON rather than assert on the object in its
entirety.

Fix index tests following Mango maximum key value patch

---

CHANGES.rst
src/cloudant/__init__.py
src/cloudant/_common_util.py
src/cloudant/client.py
tests/unit/client_tests.py
tests/unit/cloud_foundry_tests.py

Allow service name to be specified when instantiating from VCAP.
```python
with cloudant_bluemix(vcap_services, instance_name='foo', service_name='bar') as client:
...
```
_OR_
```python
client = Cloudant.bluemix(vcap_services, instance_name='foo', service_name='bar')
```
Add additional kwarg `service_name` to `CloudFoundryService`.
Includes additional unit tests.
Fixes #330.

Allow service name to be specified when instantiating from VCAP

---

CHANGES.rst
src/cloudant/replicator.py
tests/integration/replicator_test.py
tests/unit/replicator_tests.py

Removed source/target optional parameters from `create_replication`.
- Remove constructor parameters and docstring
No new tests.
Removed reference of `source/target` parameters in `integration/replicator_test.py`.
Deleted replication document in `test_replication_with_generated_id` after test completed.
fixes #341

Removed source and target optional parameters from replicator API

---

pylintrc
src/cloudant/database.py
src/cloudant/document.py
src/cloudant/replicator.py
test-requirements.txt

Fix pylint issues and have code rated 10/10.
- Disabled ‘keyword-arg-before-vararg’ pylint warning
- removed return statement to fix pylint ’inconsistent-return-statements’
CI passing, lint version changes only.
fixes #343 
**For discussion:** I’ve disabled warnings for ‘keyword-arg-before-vararg’.  If we want to enable this warning, it would require re-working the `error` module and making changes to all exception calls.

343 fix pylint 1.8.1

---

CHANGES.md
src/cloudant/design_document.py
tests/unit/design_document_tests.py

Support `/_search_disk_size` search endpoint.
Added new method `DesignDocument.search_disk_size`.
- Calls `GET databasename/_design/{ddoc}/_search_disk_size/{search_index}`.
- Returns results as dictionary.
- Raises `requests.exceptions.HTTPError` on bad status code.
Includes additional unit test.
Fixes #357.

Support '/_search_disk_size' search endpoint

---

tests/unit/database_tests.py
tests/unit/design_document_tests.py
tests/unit/unit_t_db_base.py

Added `skip_if_iam` decorator to skip tests when running with IAM auth.
No new tests.
Skips tests when IAM is enabled:
```
tests.unit.database_tests.DatabaseTests.test_create_doc_with_update_handler
tests.unit.database_tests.DatabaseTests.test_update_doc_with_update_handler
tests.unit.design_document_tests.DesignDocumentTests.test_rewrite_rule
```
fixes #376

376 skip tests when running with IAM auth

---

CHANGES.md
src/cloudant/__init__.py
src/cloudant/_common_util.py
src/cloudant/_messages.py
src/cloudant/client.py
tests/unit/client_tests.py
tests/unit/cloud_foundry_tests.py
tests/unit/unit_t_db_base.py

Updated VCAP to support IAM API key and username/password credentials.
- Updated CloudFoundryService to create a client session using IAM API key in VCAP
- Added iam_api_key property
- Handle cases when IAM or legacy credentials do not exist
- Added test cases to verify new IAM/creds case logic
- Updated sample VCAP dictionaries in `CloudFoundryServiceTests`.
- Verify VCAP with IAM and legacy creds
- Assert new logic by creating VCAP client with either IAM or legacy creds
- If IAM key is missing and either/both username and password are missing, throw exception

Added support for IAM API key in cloudant_bluemix method

---

CHANGES.md
docs/getting_started.rst
src/cloudant/database.py
tests/unit/database_tests.py

I added 2 things, I needed both of them at the same time so I ended up doing a single PR instead of 2, sorry for that.
* Move  `create_query_index` from `CloudantDatabase` to `CouchDatabase` as the JSON indexes for Mango queries are now part of CouchDB.
* Add a feature to allow checking if a document exists in a DB without having to resort to try-catch blocks, using standard `dict` syntax:
```Python
_id = 'julia30'
doc_exists = _id in my_database
if doc_exists:
print('doc with _id julia30 exists in DB')
```
*  `create_query_index`: move the method from one class to the other. Move the tests from Cloudant specific to CouchDB.
* Add a `dict` override for `__contains__` that checks in the remote DB if the document exists.
Create a `CouchDatabase` object and call the `create_query_index` the …

Query index in couchdb and support dict syntax: _id in database

---

CHANGES.md
src/cloudant/_client_session.py
src/cloudant/client.py
src/cloudant/replicator.py
tests/unit/replicator_mock_tests.py
tests/unit/replicator_tests.py

Support IAM authenticated databases when replicating.
Expose the IAM API key via the client session and inject into the replication document where applicable. 
Includes additional mock unit tests.
Fixes #354.

Support IAM authentication in replication documents

---

src/cloudant/client.py
src/cloudant/replicator.py
src/cloudant/scheduler.py
tests/unit/replicator_tests.py
tests/unit/scheduler_tests.py

Add support for `_scheduler` endpoints
Added mock tests to `scheduler_tests.py`. Note that because `_scheduler/jobs` only lists running jobs, reliably testing against a real server is difficult and prone to timing errors.
See #347 
Docstrings, CHANGELOG

Add support for _scheduler endpoints

---

.travis.yml
CHANGES.md
tests/unit/changes_tests.py
tests/unit/database_tests.py
tests/unit/db_updates_tests.py
tests/unit/document_tests.py
tests/unit/unit_t_db_base.py
tests/unit/view_tests.py

- Updated COUCHDB_VERSION variable to just contain version number
- Get couchdb node name from _membership only if CouchDB version is 2.1.1
- Updated tests to support CouchDB 1.7.x
- Added helper method to check what version
- Removed javascript validation test that doesn’t apply to CouchDB 1.7.1
Added CouchDB 1.7.1 to travis test matrix and updated Python 3.5 env to 3.6.
- Updated logic to check if COUCHDB_VERSION starts with 1 for skipping tests when running against CouchDB 1.6.x and 1.7.x.
- Only get the CouchDB node name from _membership if CouchDB version is 2.1.1
- Added helper method to check if CouchDB version is 1.x
No new tests.
Removed `test_view_callable_with_invalid_javascript` in `view_tests.py` …

Updated Travis to run against CouchDB 1.7.1 and Python 3.6

---

CHANGES.md
docs/getting_started.rst
src/cloudant/document.py
tests/unit/document_tests.py

We mention that the `Document` context manager will [not raise an exception when the document id is not found](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/document.py#L327-L329).  Unfortunately this isn't the case and a `CloudantDocumentException` is thrown.
This PR fixes `fetch()` to handle context manager cases when the document id doesn't exist and the user wants to create a new doc.
- Return from `fetch` function early if the document id doesn't exist and if `fetch` was called within the entry context manager logic
- Updated getting started example
Added `test_document_context_manager_no_doc_id` test.
fixes #361

Fixed document context manager when document id does not exist

---

CHANGES.md
src/cloudant/document.py
tests/unit/document_tests.py

Stopped incorrect raising of exception after successful retry in `doc.update_field`.
Fixes #393 
Moved the exception `raise` into an `else` block to prevent it being raised after successful execution of the recursive call into `_update_field`.
- "No change"
- "No change"
- Added new tests for conflict retry cases:
- `test_update_field_maxretries` - checks that the exception is raised when `max_tries` is exhausted
- `test_update_field_success_on_retry` - checks that an exception is not raised when a retry succeeds
- "No change"

Stopped raising exception on conflict retry success

---

CHANGES.md
src/cloudant/document.py
tests/unit/document_tests.py

Allow a user to specify a custom JSON encoder and decoder for a `Document` type.
Pass additional kwargs `encode` & `decode` in via the `Document` constructor.
See test for example usage.
Add additional kwargs to method call. No breaking API changes.
No change.
Adds `tests/unit/client_tests.py:ClientTests.test_constructor_with_url`.
No change.

Add custom JSON encoder/decoder option to `Document` constructor

---

pylintrc
src/cloudant/_common_util.py
src/cloudant/client.py
src/cloudant/database.py
src/cloudant/document.py
src/cloudant/feed.py
src/cloudant/index.py
src/cloudant/result.py
src/cloudant/scheduler.py

Fix pylint warning messages
**Note**: I tried to set a specific version of `pylint` in test-requirements.txt but unfortunately there's different versions for this package in Python 2 and 3.  Python 3 has 2.1.1 as the latest, Python 2 has 1.9.3 as the latest.
Pylint warning messages in client, database, document, index, result, and scheduler required attention.
One warning message was added to the disable list in `pylintrc`.
`useless-object-inheritance` is a warning message for Python 3.  This one is problematic in Python 2 which requires the `object` inheritance.  It's unfortunate that this warning was added because it's not backward compatible
- "No change"
- "No change"
N/A pylint changes
- "No change"

Fix pylint warning messages

---

CHANGES.md
src/cloudant/result.py

Two request are executed when only one request is required for getting a result collection that is less than the `page_size` value.
Fixes #403
Break out of `while` loop in `Result.__iter__` when the length of `result` is less than the page size.
- "No change"
- "No change"
- No new tests.
- Verified that only one request is executed in local CouchDB logging
- "No change"

403 remove unnecessary request in Result iteration

---

CHANGES.md
src/cloudant/_common_util.py
src/cloudant/feed.py
tests/unit/changes_tests.py

Allow arbitrary query parameters to be passed to custom changes filters.
Fixes #402.
Add new `ANY_ARG` and `ANY_TYPE` to list of valid changes arguments:
```py
_CHANGES_ARG_TYPES = {
'conflicts': (bool,),
'doc_ids': (list,),
'filter': (STRTYPE,),
'include_docs': (bool,),
'style': (STRTYPE,),
ANY_ARG: ANY_TYPE  # pass arbitrary query parameters to a custom filter
}
```
No change.
No change.
Includes additional unit test.
No change.

Allow query parameters to be passed to custom changes filters

---

.travis.yml
CONTRIBUTING.md
Jenkinsfile
tests/unit/auth_renewal_tests.py
tests/unit/changes_tests.py
tests/unit/client_tests.py
tests/unit/database_tests.py
tests/unit/db_updates_tests.py
tests/unit/design_document_tests.py
tests/unit/document_tests.py
tests/unit/index_tests.py
tests/unit/infinite_feed_tests.py
tests/unit/query_result_tests.py
tests/unit/query_tests.py
tests/unit/replicator_tests.py
tests/unit/result_tests.py
tests/unit/security_document_tests.py
tests/unit/view_execution_tests.py
tests/unit/view_tests.py

Added attributes for running integration tests that use a database separately from "true" unit tests.
Tagged tests that require a real database:
* `db` attribute with a database name `cloudant` and/or `couch`
* `couchapi` attribute for tests that only run on a specific api level
Added test filtering by attributes to `Travis` and `Jenkinsfile`.
Removed test skips that can now be controlled by attributes - note there are still some other remaining test skip environment variables.
- "No change"
- "No change"
- Modified existing tests because ...
- "No change"

Added test attributes

---

CHANGES.md
Jenkinsfile
src/cloudant/_client_session.py
src/cloudant/_common_util.py
src/cloudant/client.py
src/cloudant/database.py
src/cloudant/design_document.py
src/cloudant/document.py
src/cloudant/index.py
src/cloudant/query.py
src/cloudant/scheduler.py
src/cloudant/security_document.py
src/cloudant/view.py
tests/unit/client_tests.py
tests/unit/database_tests.py
tests/unit/design_document_tests.py
tests/unit/iam_auth_tests.py
tests/unit/scheduler_tests.py

Replace usage of requests built-in `response.json()` method.
Fixes #409 
Requests preferentially imports `simplejson` if it is present in the environment, overriding use of the system `json` module. This causes issues with our use of the default `json.JSONDecoder`. Since it is unclear whether requests will make a fix before version 3.x we need to workaround the problem.
Instead of calling `response.json()` we can call `json.loads(response.text)`, however, since later we may wish to return to `response.json()` (e.g. when requests 3.x is available) then it makes sense to do this in `_common_utils`.
* Replaced `response.json()` calls with `_common_util.response_to_json_dict()`.
* Added `CHANGES` entry.
- Clarified types of JSON encoder and decoder in doc strings.
- "No change"
The existing …

Replaced usage of requests `response.json()` method

---

CHANGES.md
src/cloudant/_client_session.py
src/cloudant/_common_util.py

Added `encoding='utf-8'` to responses to avoid slow `chardet` path.
Fixes #414 
Check if the repsonse encoding is unset and if so set it to `utf-8`.
(Unrelated) Removed unnecessary`pass` statements causing lint failures.
- "No change"
- "No change"
- No new tests because this path is covered by existing tests. We don't have any performance tests where we could automatically validate that this fix works or check for regressions.
- "No change"

414 decode content

---

CHANGES.md
src/cloudant/query.py
src/cloudant/result.py

Correct docsting for argument param `selector` from `str` to `dict`
Fixes #424
Find `selector` in the library and correct documentations
- No change
- No change
- No new tests because it's only change in documentations
- No change

correct docsting for param `selector` from str to dict

---

CHANGES.md
src/cloudant/database.py
src/cloudant/query.py
src/cloudant/result.py

Fixed type for `selector` in docstring of the `get_query_result` function.
fixes #424 
- Updated `str` to `dict` in `get_query_result` docstring
- Merged @thesimj's work into this branch (483ff9b) that updates the parameter for `selector` in `query.py` and` result.py `docstrings.
- "No change"
- "No change"
N/A
- "No change"

Fixed type in docstring for get_query_result

---

CHANGES.md
docs/conf.py
docs/getting_started.rst
src/cloudant/document.py
tests/unit/document_tests.py

Fix bug where document CM performed save in event of uncaught exception.
No change.
No change.
Includes 2 additional unit tests.
No change.

Stop document context manager from saving if an error is raised.

---

CHANGES.md
src/cloudant/document.py
tests/unit/document_tests.py

Removing _document_id logic so dict's updating methods work by default.
Fixes #430 
Removed _document_id logic from Document class, now everything works based in `_id` property instead.
- "No change"
- "No change"
- No new tests because current ones are enough
- "No change"

Removed document._document_id logic

---

src/cloudant/client.py

Fixed `no-else-raise` pylint warning
Removed else block in `client.py`
- "No change"
- "No change"
- "No change"
- "No change"

Fix no-else-raise pylint warning

---

CHANGES.md
src/cloudant/client.py
src/cloudant/result.py
tests/unit/query_result_tests.py
tests/unit/result_tests.py
tests/unit/unit_t_db_base.py

Make `Result`'s iteration faster paginating by `startkey` instead of `skip`.
Fixes #436 
As per #436 , paginating by `skip` could be super-slow. This patch fix the problem by using `startkey` so every iteration run in constant time.
- "No change"
- "No change"
- No new tests because current ones are enough
- "No change"

paginate by startkey

---

CHANGES.md
Jenkinsfile
docs/getting_started.rst
src/cloudant/_common_util.py
src/cloudant/client.py
src/cloudant/database.py
src/cloudant/design_document.py
src/cloudant/index.py
src/cloudant/query.py
src/cloudant/view.py
tests/unit/database_partition_tests.py
tests/unit/unit_t_db_base.py

Add partitioned databases feature.
See [partitioned_databases.rst](https://github.com/cloudant/python-cloudant/blob/63f58a4b219da63cc945771db8d07725f95af1b8/docs/partitioned_databases.rst).
New API (non-breaking).
No change.
Includes additional testing.
No change.

Partitioned databases

---

src/cloudant/result.py

Working on #437 I've noticed this one that is trivial but effectively halves memory utilization during iteration. As we release ram before `yield` we let users exploit their memory for doing whatever they would (I've seen people/comments in the wild speaking about documents > hundred MB in size).
We could elaborate further implementing a FIFO on the iterator three lines below, eg. with a deque that pops while iterating but this one alone already effectively halves ram.
- "No change"
- "No change"
- No new tests because current ones are enough
- "No change"

halves memory usage Result iterator side

---

CHANGES.md
src/cloudant/client.py
src/cloudant/error.py
tests/unit/client_tests.py

Update `create_database` to raise exception when database name is invalid.
Fixes #446 
Added additional `if` to raise `CloudantDatabaseException` when status code is `400`.
"No change"
"No change"
Added new test `test_create_invalid_database_name`
"No change"

Raise exception when database name is invalid

---

tests/unit/client_tests.py

Run tests with only `IAM_API_KEY` and `CLOUDANT_ACCOUNT`, but no `DB_USER` or `DB_PASSWORD`.
Tests to use IAM credentials and pass.
Two tests failed:
* `test_bluemix_constructor_specify_instance_name`
* `test_cloudant_bluemix_dedicated_context_helper`
Note these tests pass during the current `master` build because _both_ legacy credentials _and_ IAM credentials are supplied - meaning that these two tests pass with the supplied legacy creds instead of the IAM creds.
Skip running these tests when using IAM credentials.
These bluemix initialization tests make a connection to the service to test the init worked correctly. They use a username and password combination so can't work with an IAM API key without additional switching. While they pass in cases where both legacy creds and IAM creds …

Added skip_if_iam to some tests that rely on a legacy password

---

src/cloudant/_common_util.py

Using or importing the ABCs from 'collections'
instead of from 'collections.abc' is deprecated, and in 3.8 it will stop
working.
1) start your python3 interpreter with -Wd so it shows deprecation warnings
2) `import cloudant._common_util`
The import should work wihout warnings
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import Sequence
```
Use the error message suggested change
- "No change"
- "No change"
I don't know how (and if it's necessary for this change, actually) to test an import change like this. But if you have any ideas, let me know!

Fix "DeprecationWarning" from "collections"

---

src/cloudant/_common_util.py

f2c1298 accidentally broke the build as collections.abc is only available in Python 3.x.
This commit adds a workaround that enables the import that works both on 2 and 3.
"No change"
No new tests because the change is not semantic.
"No change"

Fix broken Python 2 build

---

tests/unit/design_document_tests.py
tests/unit/index_tests.py

The most recent RC builds include metadata changes that mean disk_size has been removed. The test will now pop disk_size if it exists. There is also changes to the format of warnings.   
Fixed up the test DesignDocumentTests::test_get_info - the most recent RC builds include meta data changes that mean disk_size has been removed. The test will now pop disk_size if it exists. 
Fixed up the test CloudantIndexExceptionTests::test_index_usage_via_query - the most recent RC builds include warning message format changes - instead of responding with `no matching index found` the database responds with `No matching index found`. The test will now `.lower()` the warning message.
No change
No change
Run the tests against the latest RC build and assert they pass.
No change

Fixup unit tests Broken by Couch3 

---

tests/unit/design_document_tests.py

Updated `_search_info` tests to trigger index build
For PRs without an associated issue and/or test/build issues
Run tests:
* `tests.unit.design_document_tests.DesignDocumentTests.test_get_search_disk_size`
* `tests.unit.design_document_tests.DesignDocumentTests.test_get_search_info`
Tests to pass
Assertions fail with:
* `False is not true : The disk_size should be greater than 0.`
Update tests to ensure a search index build is triggered before asserting metadata.
- "No change"
- "No change"
- Modified existing tests to trigger search index build.
- "No change"

Trigger search index builds before asserting metadata

---

tests/unit/design_document_tests.py

The data_size field is no longer present in CouchDB 3.x so remove it from the assertion for compatibility.
Removed data_size from view info assertion
* Run `tests.unit.design_document_tests.DesignDocumentTests.test_get_info` with CouchDB 3 rc1
Test to pass
Assertion failure:
```
{'vie[33 chars]se, 'waiting_clients': 0, 'waiting_commit': Fa[104 chars]001'} != {'vie[33 chars]se, 'update_seq': 0, 'waiting_clients': 0, 'wa[120 chars]001'}
{'name': 'ddoc001',
'view_index': {'compact_running': False,
+                 'data_size': 0,
'language': 'javascript',
'purge_seq': 0,
'update_seq': 0,
'updater_running': False,
'waiting_clients': 0,
'waiting_commit': False}}
```
Remove the `data_size` element from the view info before asserting as it is no longer present in CouchDB 3.
- "No change"
- "No …

Removed data_size from view info assertion

---

.travis.yml
Jenkinsfile
tests/unit/client_tests.py
tests/unit/replicator_tests.py
tests/unit/unit_t_db_base.py

Adjust read timeout in intermittently failing test and update test matrices.
Run `tests.unit.replicator_tests.ReplicatorTests.test_timeout_in_create_replication`
Test to pass.
It intermittently fails.
Change the timeout from `.5` to `(30,5)` - this means the connect timeout stays at the default 30s instead of also being reduced to .5s and the read timeout is increased from .5 seconds to 5 s. Whilst this means the test takes longer to run, it is much more reliable.
- "No change"
- "No change"
- Modified existing tests because to change timeout to resolve intermittent failure.
- Modified test matrix to remove Python 2 as it is EOL.
- Modified test matrix for CouchDB version
*  `1.7.1` -> `1.7.2` (although Couch 1.x is EOL, we'll still run these tests until the next major I think)
* Had to …

Intermittent read timeout

---

CHANGES.md
src/cloudant/design_document.py
tests/unit/database_partition_tests.py
tests/unit/database_tests.py
tests/unit/design_document_tests.py

In CouchDB 3.0.0, when attempting to create a design document with `partitioned=false`, the cloudant still creates the design doc with `partitioned=true`
Fixes #466 
In the **src/cloudant/design_document.py**, in the `__init__` function, the partition options were being set only when` partition=true`.
I added an else clause to set partition option when partition flag is `false`.
No change
No change
Modified existing test **design_document_tests.py** because it already contains relevant tests for unit testing. Added the new test function `test_correct_design_document_partitioned_true` and `test_correct_design_document_partitioned_false`
Modified existing test **database_partition_tests.py** because it already contains the test for _partitioned design doc_ …

Fixed the bug where design doc was created in CouchDB 3.0 with partition enabled even when the partition flag was false

---

src/cloudant/feed.py
test-requirements.txt
tests/unit/design_document_tests.py

The build has been failing recently with a false positive linter error.
Pylint was complaining that a method is not callable, even though
the method is defined right on the following line.
As I could not find either the reason pylint was failing or a
solution that resolves this issue, this commit disables the check for
that specific line pylint was failing on.
Links to failed runs: https://cloudant-sdks-jenkins.swg-devops.com/job/Main/job/python-cloudant/job/master/28/display/redirect and https://cloudant-sdks-jenkins.swg-devops.com/job/Main/job/python-cloudant/job/master/29/display/redirect
I was able to reproduce both the issue and the fix locally.
- "No change"
- "No change"
- Build only changes
- "No change"
Note to reviewers: the file prior to this commit was last changed in …

Disable false-positive linter error

---

CHANGES.md
docs/getting_started.rst
src/cloudant/database.py
src/cloudant/index.py
tests/unit/index_tests.py

The issue is described in #468 .
`create_query_index` does not always supply `partitioned` which is
always required by the service.
This PR changes the behavior that so that `partitioned` is now always
present in the `create_query_index` requests.
~~- "No change"~~
EDIT: Two default `False` parameters have been changed to `None`. The users should not notice any difference.
- "No change"
- Added new test case
- "No change"
This fixes #468

Make `create_query_index` always supply `partitioned`

---

CHANGES.md
setup.py

This fixes https://github.com/cloudant/python-cloudant/issues/476
See related https://stackoverflow.com/a/10971047/5323166

Make setup.py compatible with python 2

---

CHANGES.md
src/cloudant/database.py
src/cloudant/query.py
src/cloudant/result.py

The docs for `bookmarks` was incorrect. This PR fixes that.
- "No change"
- "No change"
- Docs only change
- "No change"

Remove incorrect restriction from docs for bookmarks

---

CHANGES.md
src/cloudant/replicator.py
tests/unit/replicator_tests.py

Correct the list of valid replicator states
Fixes #464 
* Add the `failed` state to `follow_replication` since this is another condition under which it should exit in CouchDB 2.1+.
`follow_replication` exits for the `error` state even though that is a retryable state in CouchDB 2.1+ systems, it was existing behaviour for Couch < 2.1. Using the `error` state as an exit condition is retained so the code continues to operate in the same way as it has since launch when interacting with CouchDB >=2.1 based servers.
Behaviour change for the `failed` state which should have ended `follow_replication` but didn't, this is a fix.
- "No change"
The replicator tests were missing some other states introduced in CouchDB 2.1 scheduler.
- Modified existing tests because they did not have the complete …

Correct replicator states

---

CHANGES.md
src/cloudant/result.py
tests/unit/database_tests.py

When querying a grouped view where either a) there's more documents than the default page size or b) there's more documents that the user-defined page size option, a `KeyError` occurs.  This happens when the view data iteration logic tries to retrieve the next set of results.
When querying a grouped view where pagination is needed, a `KeyError` occurs when trying to grab the next page.  This error is happening because the iteration logic is expecting an `id` field which does not exist for grouped view results.
fixes #456 
Update [line 400 in `cloudant/result.py`](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/result.py#L400) to check that the `id` field exists.
Added new test `DatabaseTests.test_retrieve_grouped_view_result_with_page_size`.

Fix result paging for grouped view queries

---

MIGRATION.md

Replication related operations were missing from the migration guide.
I added some replication and scheduler related missing operations in the migration guide table. There was not identical operation like `postReplicate`, so I removed it.
- "No change"
- "No change"
- "No change"
- "No change"

Add replication and scheduler operations to the migration guide

---

CHANGES.md
Jenkinsfile
src/cloudant/client.py
tests/unit/client_tests.py

Change the test server configuration and allow for overriding the token server used by tests.
Fix `Cloudant.bluemix()` handling of username/account.
Run Jenkins with a custom IAM token server.
Tests to pass.
Test failures.
* Add `IAM_TOKEN_URL` environment variable to IAM test runs
* Add new env vars and cred IDs to `Jenkinsfile` - use `DB_URL` instead of `CLOUDANT_ACCOUNT`
* Fix tests to work with above (see "Testing" below)
The `Cloudant.bluemix()` function was assuming that the username was the account name. This does not work with the new style account credentials where username does not match account name. The URL was already being correctly provided, so just use `None` as the account name instead.
- "No change"
- "No change"
- Modified existing tests because many made the assumption …

Update test server config

---

CHANGES.md
src/cloudant/_common_util.py
tests/unit/database_tests.py
tests/unit/param_translation_tests.py

Fixes https://github.com/cloudant/python-cloudant/issues/221#issuecomment-752424499
Used custom encoder at `_py_to_couch_translate` for `endkey`, `key`, and `startkey` parameters.
`endkey`, `key` and `startkey` parameters will be encoded with the custom encoder.
- No change
Test that all_docs uses the custom encoder. Fixed `test_valid_endkey`, `test_valid_key` and `test_valid_startkey ` with long type.
- No change

Use custom encoder (if provided) for all view `key` params not just `keys`

---

CHANGES.md
src/cloudant/_common_util.py
tests/unit/param_translation_tests.py

Fixes #494 
Allow bool type for `endkey`, `key`, and `startkey`. 
- No change
- No change
Edited the `invalid` tests to use `{'foo': 'bar'}` invalid values instead of booleans, and extended the existing tests to validate boolean types.
- No change

Support boolean type for `key`, `endkey`, and `startkey` in view requests

---

CHANGES.md
src/cloudant/database.py
tests/unit/database_tests.py

Merges #474 and tests.
One sentence in the pydoc was a little bit misleading, so I changed it to:
> Dictates whether a remote request is made to retrieve the doc, if it is not present in the local cache.
Extended the tests to cover the new behaviour based on the proposed behaviour table.
| Call | Doc is local | Doc is remote | Result | Covered with tests |
| --- | --- | --- | --- | --- |
| `db['foo']` | `True` | `True` | returns local doc | test_create_document_that_already_exists<br>test_create_document_without_id<br>test_create_design_document<br>test_create_empty_document
| `db['foo']` | `False` | `True` | returns remote doc | test_get_document_from_remote |
| `db['foo']` | `False` | `False` | returns `KeyError` | test_get_non_existing_doc_via_getitem
| `db['foo']` | `True` | `False` | …

Override dict's get method

---

tests/unit/changes_tests.py

This assertion removal fixes failed pipeline. Comparing seq lengths is not grounded in any contract of the API.
I removed the assertion regarding `seq` length comparison.
- "No change"
- "No change"
- Modified existing tests because comparing seq lengths is not grounded in any contract of the API.
- "No change"

Remove assertion from test_get_feed_descending

---

tests/unit/changes_tests.py
tests/unit/client_tests.py
tests/unit/database_partition_tests.py
tests/unit/database_tests.py
tests/unit/design_document_tests.py
tests/unit/document_tests.py
tests/unit/iam_auth_tests.py
tests/unit/index_tests.py
tests/unit/replicator_mock_tests.py

The deprecated aliases have been removed in Python 3.11 in https://github.com/python/cpython/pull/28268
- "No change"
- "No change"
- "No change"

Use assertEqual instead of assertEquals for Python 3.11 compatibility.

---

MIGRATION.md

There have been some questions regarding migration lately. This PR tries to address them.
I clarified some of the questionable topics in this change:
* where users should check the server errors and the authentication errors
I also fixed a typo from python-java-sdk to cloudant-python-sdk
My IDE lately breaks the lines automatically, I have not figured out how I can turn it off yet, but I think this is a great feature, and it helps the reviewers to read the long lines more effectively, so I kept these modifications.
- "No change"
- "No change"
- N/A
- "No change"

[MIGRATION] Add note about authentication errors and server errors
