cloudant/python-cloudant

CHANGES.rst, docs/getting_started.rst, src/cloudant/database.py, src/cloudant/document.py, src/cloudant/query.py, src/cloudant/result.py, src/cloudant/views.py
_What:_
- Added query management functionality to the library.  Resolves #39.
- Unit tests are complete but will be included in a follow up PR to keep the review process relatively manageable.  All unit tests have run successfully to completion.
- Index management is **NOT** included in this PR either, it will also be included in a future PR.
_Why:_
The library needs to provide query management functionality so that users do not have to access query functionality directly via the `_find` endpoint.
_How:_
- Added a Query class and query.py module to handle query parameter processing and request execution to the `_find` endpoint. Found in 4ff83bc.
- Added a QueryResult class to the result.py module to handle slicing and iteration of query results.  Found in 4ff83bc.
- Added a convenience …
=> Add query execution support - part one

tests/unit/db/design_document_tests.py, tests/unit/db/views_tests.py
_What:_
Add index management unit tests for the design_documents and views modules in support of #40.
_Why:_
To ensure that the updated design_document and views index management logic is thoroughly tested.
_How:_
- Update the design_document_tests module with index management tests.
- Update the views_tests module with index management tests.
- Add a QueryIndexViewTests class to test QueryIndexView functionality.
_Issues:_
- #76 in support of #40 
reviewer: @evansde77 
reviewer: @ricellis
=> Add index management unit tests for the design_documents and views modules

tests/unit/db/database_tests.py
_What:_
Add index management unit tests for the database module in support of #40.
_Why:_
To ensure that the updated database index management logic is thoroughly tested.
_How:_
- Update the database module with index management tests.
_Issues:_
#78 in support of #40
reviewer: @evansde77 
reviewer: @emlaver
=> Add index management unit tests for database module

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Create templates for issues and pull requests to help library users to provide all
the information we require.
reviewer @alfinkel
=> Create Templates for Issues and Pull Requests.

CHANGES.rst
Add entry in CHANGES.rst for the modules that were renamed in PRs #136, #138, #140, #141.
No additional tests.
=> CHANGES.rst entry for renaming modules

CONTRIBUTING.rst
I added a couple of notes to help people get to running the tests.
Modified CONTRIBUTING.md
I can run the tests, but it'd be good to know why they all fail before we merge the PR (do I need to set up a Cloudant account/database?).
Leave this section blank, its to allow us to easily see who is reviewing this pull request.
- #88 
This is just a quick listing of the commands to clone the repo and get to a stage where you can run the tests.
=> Add development quickstart commands

CHANGES.rst, src/cloudant/design_document.py, tests/unit/design_document_tests.py
Support info and search info endpoints in design document module.
- Added info and search_info methods in design_document.py
Added test cases in DesignDocumentTests.
fixes #190
=> Added support for info and search info endpoints

src/cloudant/database.py
Fixed incorrect code example for `src.cloudant.database.CouchDatabase#changes`
Documentation.
Fixes #194
=> Corrected changes example doc

tests/unit/design_document_tests.py
Split dbcopy assertions into separate test
Leave the dbcopy information in whatever location it is stored in the design document without trying to change behaviours for different versions.
Isolate testing of `dbcopy` from `test_fetch_map_reduce` in new `test_fetch_dbcopy`.
Update assertion to use new Cloudant location for CI testing.
Removed `dbcopy` parameter from tests where it is not used.
Fixes #207
=> Split dbcopy assertions into separate test

docs/getting_started.rst
- Changed nonexistent attribute `client.cloudant_url` to `client.server_url`
- Added `connect=True` to client constructor
No tests added.
fixes #250
=> 250 update endpoint access example in getting started

docs/getting_started.rst
- information on instantiating the library so that it can be shared
- thread safety from `urllib3` used in `requests` library
- describe how to configure connection pooling
- describe how the library authenticates to Cloudant (using cookie or basic authentication)
- describe if session expiry gets handled automatically by the library
- how to use the library in common python application server environments (e.g. django, flask, gunicorn) so that connection pooling can be configured at the app server level
- Added connection pooling, resources, and cookie auth to `getting_started.rst`
fixes #18
=> 18 add connection pooling to getting started documentation

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.rst, DCO1.1.txt
Update `CONTRIBUTING.rst` with DCO instructions.
n/a
n/a
n/a
=> Update CONTRIBUTING.rst with DCO instructions

docs/getting_started.rst
Make examples in `getting_started.rst` compatible with Python 3.
=> Make examples compatible with Python 3

CHANGES.rst, src/cloudant/__init__.py, tests/unit/client_tests.py
Fix client construction in `cloudant_bluemix` context manager.
Change `cloudant_user` and `auth_token` to positional arguments.
Includes additional unit test.
Fixes #311.
=> Fix client construction in cloudant_bluemix context manager

docs/getting_started.rst
Update `Document` CM usage in 'Getting Started' docs.
Add warning about using `.delete()` method inside CM.
Fixes #317.
=> Update Document CM usage in docs/getting_started.rst

Jenkinsfile, tests/unit/auth_renewal_tests.py, tests/unit/client_tests.py, tests/unit/database_tests.py, tests/unit/replicator_tests.py, tests/unit/unit_t_db_base.py
Test with an IAM authenticated client.
=> Test with an IAM authenticated client

CONTRIBUTING.rst
Fixed relative link for DCO text file in CONTRIBUTING.rst.
=> Fixed DCO link

Jenkinsfile, tests/unit/auth_renewal_tests.py, tests/unit/client_tests.py, tests/unit/database_tests.py, tests/unit/replicator_tests.py, tests/unit/unit_t_db_base.py
Test with a basic access authenticated client.
=> Test with a basic access authenticated client

test-requirements.txt
Hold pylint versions at:
pylint 1.7.4
astroid 1.5.3
Updated `test-requirements.txt` with the pinned versions.
CI passing, lint version changes only.
Temporary workaround for #343
=> Pinned pylint 1.7.4 and astroid 1.5.3

CHANGES.md, docs/getting_started.rst, src/cloudant/_client_session.py, tests/unit/iam_auth_tests.py
Updated default IAM token URL.
Updated URL to `https://iam.bluemix.net/identity/token`.
Updated test environment variable name.
N/A
=> Updated default IAM token URL

docs/getting_started.rst
Add enforcing TLS 1.2 note to `getting_started.rst`.
=> Add enforcing TLS 1.2 note to getting_started.rst

CHANGES.md, src/cloudant/_common_util.py, src/cloudant/database.py, src/cloudant/result.py, tests/unit/param_translation_tests.py, tests/unit/view_execution_tests.py
Support new view parameters
Add support and documentation for extra `kwargs` to `get_view_result`: `stable` and `update`.
Added tests in `param_translation_tests.py`, `view_execution_tests.py`.
#252
=> Support new view parameters

CHANGES.md, docs/getting_started.rst, src/cloudant/_client_session.py
Update the default IAM token server URL.
No change.
No change.
No change.
No change.
=> Update the default IAM token server URL

CHANGES.md, docs/getting_started.rst, test-requirements.txt
Added `get_query_result` example to getting started
Fixes #355 
Updated docs, no code change
- "No change"
- "No change"
N/A doc only changes
- "No change"
=> Added get_query_result example to getting started

tests/unit/document_tests.py
Fixed a document test mock
Fixes #431 
Reimplemented a mock so doc.save() gets called during update_field and not mock construction/evaluation. Tests were passing because `update_field` did not called save() at all, thus making it difficult to spot.
- "No change"
- "No change"
- Modified `test_update_field_success_on_retry`
- "No change"
=> Fixing test_update_field_success_on_retry

tests/unit/database_tests.py
Mock server responses for `DatabaseTests.test_get_set_revision_limit`.
These changes are required because the `PUT /db/_revs_limit` endpoint has been disabled in the Cloudant service.
=> Mock server responses for DatabaseTests.test_get_set_revision_limit.

src/cloudant/result.py
Hello, this PR implements a deflating FIFO Result iterator. To me, this is especially useful when I run large multiprocessing ingestion batches where having as little allocated ram as possible give a better scalability. While we could obtain somethin similar reverse()ing lists, manual states that `collection` types are [more efficient](https://docs.python.org/2/library/collections.html#deque-objects).
- "No change"
- "No change"
- No new tests because current ones are enough
- "No change"
=> slimming Result iterator

CHANGES.md
Set CHANGES.md to 100 char limit.
=> Set CHANGES.md to 100 char limit.

setup.py
Use the README as the package description here https://pypi.org/project/cloudant/.
=> Include README in package metadata.

src/cloudant/database.py
s/get_list_result/get_list_function_result/
=> Update documentation to match function signatur

.github/PULL_REQUEST_TEMPLATE.md
This repo only has a `CHANGES.md` and `CHANGELOG.md` is not applicable.
This PR removes the `CHANGELOG.md` reference from the template.
=> Remove `CHANGELOG.md` from the PR template

docs/getting_started.rst
Update documentation with usage for service endpoints not in the cloudant.com domain.
Documentation
- "No change"
- "No change"
- Checked the documentation look with [reStructuredText extension in VSCode](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext):
- "No change"
=> Add private endpoint usage with IAM to the documentation

MIGRATION.md
Migration guide updates:
- Replaced `create` with `save` local doc operation. The `save` operation with use `create` under-the-covers if the document doesn't exist. 
- Group together local doc operations
- Fix API doc link for local doc delete operation
=> Updates to local document operations in migration guide

.travis.yml
Remove testing matrix against CouchDB 1.7.x in Travis CI.
=> Remove CouchDB 1.x from Travis CI

MANIFEST.in
=> Include LICENSE in pip package

CHANGES.md, README.md, src/cloudant/__init__.py
Add deprecation notice
Add notice to README, CHANGES and log a warning for developers.
Deprecation notice, library EOL.
- "No change"
- N/A documentation
- Manually tested warning emitted when running with `-Wd`
- Added `DeprecationWarning`, visible when running with `-Wd`, see [pyhton warnings doc](https://docs.python.org/3/library/warnings.html#updating-code-for-new-versions-of-dependencies)
=> Add deprecation warnings

CHANGES.md, README.md, src/cloudant/__init__.py
Add EOL notice
Add notice to README, CHANGES and log a warning for developers.
EOL notice.
- "No change"
- N/A documentation
- N/A
=> doc: note full deprecation
